-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module TrackingExpenses.Object.Expenses_bac_credomatic exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import TrackingExpenses.InputObject
import TrackingExpenses.Interface
import TrackingExpenses.Object
import TrackingExpenses.Scalar
import TrackingExpenses.ScalarCodecs
import TrackingExpenses.Union


amount : SelectionSet TrackingExpenses.ScalarCodecs.Float8 TrackingExpenses.Object.Expenses_bac_credomatic
amount =
    Object.selectionForField "ScalarCodecs.Float8" "amount" [] (TrackingExpenses.ScalarCodecs.codecs |> TrackingExpenses.Scalar.unwrapCodecs |> .codecFloat8 |> .decoder)


card_number : SelectionSet String TrackingExpenses.Object.Expenses_bac_credomatic
card_number =
    Object.selectionForField "String" "card_number" [] Decode.string


card_type : SelectionSet String TrackingExpenses.Object.Expenses_bac_credomatic
card_type =
    Object.selectionForField "String" "card_type" [] Decode.string


commerce : SelectionSet String TrackingExpenses.Object.Expenses_bac_credomatic
commerce =
    Object.selectionForField "String" "commerce" [] Decode.string


currency : SelectionSet String TrackingExpenses.Object.Expenses_bac_credomatic
currency =
    Object.selectionForField "String" "currency" [] Decode.string


date : SelectionSet (Maybe TrackingExpenses.ScalarCodecs.Date) TrackingExpenses.Object.Expenses_bac_credomatic
date =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "date" [] (TrackingExpenses.ScalarCodecs.codecs |> TrackingExpenses.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


id : SelectionSet TrackingExpenses.ScalarCodecs.Uuid TrackingExpenses.Object.Expenses_bac_credomatic
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (TrackingExpenses.ScalarCodecs.codecs |> TrackingExpenses.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


location : SelectionSet String TrackingExpenses.Object.Expenses_bac_credomatic
location =
    Object.selectionForField "String" "location" [] Decode.string
