-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module TrackingExpenses.Object.Expenses_bac_credomatic_aggregate exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import TrackingExpenses.InputObject
import TrackingExpenses.Interface
import TrackingExpenses.Object
import TrackingExpenses.Scalar
import TrackingExpenses.ScalarCodecs
import TrackingExpenses.Union


aggregate :
    SelectionSet decodesTo TrackingExpenses.Object.Expenses_bac_credomatic_aggregate_fields
    -> SelectionSet (Maybe decodesTo) TrackingExpenses.Object.Expenses_bac_credomatic_aggregate
aggregate object____ =
    Object.selectionForCompositeField "aggregate" [] object____ (Basics.identity >> Decode.nullable)


nodes :
    SelectionSet decodesTo TrackingExpenses.Object.Expenses_bac_credomatic
    -> SelectionSet (List decodesTo) TrackingExpenses.Object.Expenses_bac_credomatic_aggregate
nodes object____ =
    Object.selectionForCompositeField "nodes" [] object____ (Basics.identity >> Decode.list)
