-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module TrackingExpenses.Object exposing (..)


type Expenses_bac_credomatic
    = Expenses_bac_credomatic


type Expenses_bac_credomatic_aggregate
    = Expenses_bac_credomatic_aggregate


type Expenses_bac_credomatic_aggregate_fields
    = Expenses_bac_credomatic_aggregate_fields


type Expenses_bac_credomatic_avg_fields
    = Expenses_bac_credomatic_avg_fields


type Expenses_bac_credomatic_max_fields
    = Expenses_bac_credomatic_max_fields


type Expenses_bac_credomatic_min_fields
    = Expenses_bac_credomatic_min_fields


type Expenses_bac_credomatic_mutation_response
    = Expenses_bac_credomatic_mutation_response


type Expenses_bac_credomatic_stddev_fields
    = Expenses_bac_credomatic_stddev_fields


type Expenses_bac_credomatic_stddev_pop_fields
    = Expenses_bac_credomatic_stddev_pop_fields


type Expenses_bac_credomatic_stddev_samp_fields
    = Expenses_bac_credomatic_stddev_samp_fields


type Expenses_bac_credomatic_sum_fields
    = Expenses_bac_credomatic_sum_fields


type Expenses_bac_credomatic_var_pop_fields
    = Expenses_bac_credomatic_var_pop_fields


type Expenses_bac_credomatic_var_samp_fields
    = Expenses_bac_credomatic_var_samp_fields


type Expenses_bac_credomatic_variance_fields
    = Expenses_bac_credomatic_variance_fields
