-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module TrackingExpenses.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import TrackingExpenses.Scalar exposing (defaultCodecs)


type alias Date =
    TrackingExpenses.Scalar.Date


type alias Float8 =
    TrackingExpenses.Scalar.Float8


type alias Uuid =
    TrackingExpenses.Scalar.Uuid


codecs : TrackingExpenses.Scalar.Codecs Date Float8 Uuid
codecs =
    TrackingExpenses.Scalar.defineCodecs
        { codecDate = defaultCodecs.codecDate
        , codecFloat8 = defaultCodecs.codecFloat8
        , codecUuid = defaultCodecs.codecUuid
        }
