-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Expenses.Object.Expenses_bac_credomatic_min_fields exposing (..)

import Expenses.InputObject
import Expenses.Interface
import Expenses.Object
import Expenses.Scalar
import Expenses.ScalarCodecs
import Expenses.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


amount : SelectionSet (Maybe Expenses.ScalarCodecs.Numeric) Expenses.Object.Expenses_bac_credomatic_min_fields
amount =
    Object.selectionForField "(Maybe ScalarCodecs.Numeric)" "amount" [] (Expenses.ScalarCodecs.codecs |> Expenses.Scalar.unwrapCodecs |> .codecNumeric |> .decoder |> Decode.nullable)


card_number : SelectionSet (Maybe String) Expenses.Object.Expenses_bac_credomatic_min_fields
card_number =
    Object.selectionForField "(Maybe String)" "card_number" [] (Decode.string |> Decode.nullable)


card_type : SelectionSet (Maybe String) Expenses.Object.Expenses_bac_credomatic_min_fields
card_type =
    Object.selectionForField "(Maybe String)" "card_type" [] (Decode.string |> Decode.nullable)


commerce : SelectionSet (Maybe String) Expenses.Object.Expenses_bac_credomatic_min_fields
commerce =
    Object.selectionForField "(Maybe String)" "commerce" [] (Decode.string |> Decode.nullable)


currency : SelectionSet (Maybe String) Expenses.Object.Expenses_bac_credomatic_min_fields
currency =
    Object.selectionForField "(Maybe String)" "currency" [] (Decode.string |> Decode.nullable)


date : SelectionSet (Maybe Expenses.ScalarCodecs.Date) Expenses.Object.Expenses_bac_credomatic_min_fields
date =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "date" [] (Expenses.ScalarCodecs.codecs |> Expenses.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


id : SelectionSet (Maybe Expenses.ScalarCodecs.Uuid) Expenses.Object.Expenses_bac_credomatic_min_fields
id =
    Object.selectionForField "(Maybe ScalarCodecs.Uuid)" "id" [] (Expenses.ScalarCodecs.codecs |> Expenses.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)


location : SelectionSet (Maybe String) Expenses.Object.Expenses_bac_credomatic_min_fields
location =
    Object.selectionForField "(Maybe String)" "location" [] (Decode.string |> Decode.nullable)
