-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Expenses.Object.Expenses_bac_credomatic exposing (..)

import Expenses.InputObject
import Expenses.Interface
import Expenses.Object
import Expenses.Scalar
import Expenses.ScalarCodecs
import Expenses.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


amount : SelectionSet Expenses.ScalarCodecs.Numeric Expenses.Object.Expenses_bac_credomatic
amount =
    Object.selectionForField "ScalarCodecs.Numeric" "amount" [] (Expenses.ScalarCodecs.codecs |> Expenses.Scalar.unwrapCodecs |> .codecNumeric |> .decoder)


card_number : SelectionSet String Expenses.Object.Expenses_bac_credomatic
card_number =
    Object.selectionForField "String" "card_number" [] Decode.string


card_type : SelectionSet String Expenses.Object.Expenses_bac_credomatic
card_type =
    Object.selectionForField "String" "card_type" [] Decode.string


commerce : SelectionSet String Expenses.Object.Expenses_bac_credomatic
commerce =
    Object.selectionForField "String" "commerce" [] Decode.string


currency : SelectionSet String Expenses.Object.Expenses_bac_credomatic
currency =
    Object.selectionForField "String" "currency" [] Decode.string


date : SelectionSet Expenses.ScalarCodecs.Date Expenses.Object.Expenses_bac_credomatic
date =
    Object.selectionForField "ScalarCodecs.Date" "date" [] (Expenses.ScalarCodecs.codecs |> Expenses.Scalar.unwrapCodecs |> .codecDate |> .decoder)


id : SelectionSet Expenses.ScalarCodecs.Uuid Expenses.Object.Expenses_bac_credomatic
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (Expenses.ScalarCodecs.codecs |> Expenses.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


location : SelectionSet String Expenses.Object.Expenses_bac_credomatic
location =
    Object.selectionForField "String" "location" [] Decode.string
